version: '3.7'

services:
  app:
    build: .
    command: "/app/server"
    environment:
      - connection_string_postgres=postgres://postgres:mysecretpassword@db:5432/postgres?sslmode=disable
      - address=:8080
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
